### ISSUE TITLE
Opacity filter in Safari 5.1.7

### ISSUE THREAD

**Issue by xlphs** [uxebu/bonsai#192]
It works in Safari 6 but not 5. I tested it with Orbit.

http://orbit.bonsaijs.org/#new%20Rect(100%2C%20100%2C%20100%2C%20100).attr(%7B%0AfillColor%3A%20'red'%2C%0Afilters%3A%20new%20filter.Opacity(0.2)%0A%7D).addTo(stage)%3B

Is there a workaround?

**Comment by klipstein** [comment]
Currently BonsaiJS supports filters in those browsers which support SVG filters, which are just available since Safari 6. If you want to change opacity I would suggest to work with alpha values instead (see http://docs.bonsaijs.org/overview/Color.html):

``` js
new Rect(100, 100, 100, 100).attr({
  fillColor: 'rgba(255, 0, 0, 0.2)'
}).addTo(stage);
```

http://orbit.bonsaijs.org/#var%20rect%20%3D%20new%20Rect%28100%2C%20100%2C%20100%2C%20100%29.attr%28{%0A%20%20fillColor%3A%20%27rgba%28255%2C%200%2C%200%2C%200.2%29%27%0A}%29.addTo%28stage%29%3B%0A%0Arect.animate%28%272s%27%2C%20{%0A%20%20fillColor%3A%20%27rgba%28255%2C%200%2C%200%2C%201%29%27%0A}%2C%20{%0A%20%20repeat%3A%20Infinity%0A}%29%3B%0A

To apply opacity to an image (or other display objects), you could create a Group and place an opacity layer above it:

http://orbit.bonsaijs.org/#var%20group%20%3D%20new%20Group%28%29%3B%0A%0Avar%20img%20%3D%20new%20Bitmap%28%27https%3A%2F%2Fraw.github.com%2Fmaxogden%2Fcats%2Fmaster%2Fcat_photos%2F5804b25e64d211e18bb812313804a181_7.jpg%27%29%0A%20%20.attr%28{%0A%20%20%20%20width%3A%20200%2C%0A%20%20%20%20height%3A%20200%0A%20%20}%29%3B%0A%0Avar%20rect%20%3D%20new%20Rect%280%2C%200%2C%20200%2C%20200%29.attr%28{%0A%20%20fillColor%3A%20%27rgba%28255%2C%20255%2C%20255%2C%200.5%29%27%0A}%29.addTo%28stage%29%3B%0A%0Aimg.addTo%28group%29%3B%0Arect.addTo%28group%29%3B%0A%0Agroup.addTo%28stage%29%3B%0A

Hope this helps.

**Comment by xlphs** [comment]
Thank you. RGBA worked fine.
