### ISSUE TITLE
Idea - Combining events with scheduling...

### ISSUE THREAD

**Issue by iammerrick** [uxebu/bonsai#214]
Today I was talking to @jargv about coupling less to the time itself, what do you guys think?

M

``` javascript
var rectPath = bonsai.Path.rect(150, 150, 150, 150).attr({fillColor: 'red', strokeColor: 'green', strokeWidth: 5});

stage.addChild(rectPath);

stage.frames({
  '2s': function(){
    rectPath.attr({fillColor: 'blue', opacity: 0.5});
  },
  '4s': function(){
    rectPath.attr({fillColor: 'green', opacity:1});
    this.trigger('green');
  },
  '6s': function(){
    rectPath.attr({fillColor: 'yellow'});
  },
  '7s': 'end' // Using a string will trigger the event.
});

stage.frames({
  'green + 5s' : function() {
    // When green is triggered, delay 5 seconds and run this frame.
  }
});

stage.on('end', function() {
  // Show is over folks
});

stage.on('stop', function() {
  console.log('end');
});
```

**Comment by basecode** [comment]
Thanks for your feedback!

> stage.on('stop', function() {…

Regarding events, I actually would expect Movie to have a similar API than [HTMLMediaElement](http://www.whatwg.org/specs/web-apps/current-work/multipage/the-video-element.html#mediaevents). Including the following events: loadstart, play, playing, paused, ended.

> '7s': 'end'

Regarding "end": Similar to your proposal "end" shouldn't execute a frame. It should just emit "ended" and play frame "0". It's not even necessary to define "end" explicitly. "end" is supposed to be triggered implicitly at the end of the last frame.

> this.trigger('green');

Regarding custom events: Are you saying `trigger` should emit an event on Movie class? Since `EventEmitter` is mixed in Movie class, you can use `myMovie.emit('green')` + `myMovie.on('green', fn)` instead.

> 'green + 5s' : function() {

That's a little bit too use-case specific for me. But the Movie class provides similar API:

```
stage.frames({
  …
  '4s': function() {
    rectPath.attr({fillColor: 'green', opacity:1});
    this.emit('green');
  }
  …
});

stage.on('green', function() {
    this.frames({
     '9s': function() {
       rectPath.attr({fillColor: 'white', opacity:1});
     }
    });
});
```

Edit directly in Orbit: http://goo.gl/Y6mgy

**Comment by iammerrick** [comment]
Well, it would allow you to organize scenes by event instead of time. So reordering things becomes trivial. I understand if it is too specific. Thanks for your great and timely responses! I couldn't agree more that the movie should emit those events, currently I have to introduce a microframe to prevent the movie from looping...
